"""Comprehensive NIFTY 50 constituent metadata with symbols, names, and sectors."""

from typing import Dict, List

NIFTY_50_STOCKS: List[Dict[str, str]] = [
    {"symbol": "ADANIENT.NS", "name": "Adani Enterprises Ltd.", "sector": "Metals & Mining"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports and SEZ Ltd.", "sector": "Services"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals Enterprise Ltd.", "sector": "Healthcare"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints Ltd.", "sector": "Consumer Durables"},
    {"symbol": "AXISBANK.NS", "name": "Axis Bank Ltd.", "sector": "Financial Services"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto Ltd.", "sector": "Automobile"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance Ltd.", "sector": "Financial Services"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv Ltd.", "sector": "Financial Services"},
    {"symbol": "BEL.NS", "name": "Bharat Electronics Ltd.", "sector": "Capital Goods"},
    {"symbol": "BPCL.NS", "name": "Bharat Petroleum Corporation Ltd.", "sector": "Oil, Gas & Consumable Fuels"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel Ltd.", "sector": "Telecommunication"},
    {"symbol": "BRITANNIA.NS", "name": "Britannia Industries Ltd.", "sector": "Fast Moving Consumer Goods"},
    {"symbol": "CIPLA.NS", "name": "Cipla Ltd.", "sector": "Healthcare"},
    {"symbol": "COALINDIA.NS", "name": "Coal India Ltd.", "sector": "Oil, Gas & Consumable Fuels"},
    {"symbol": "DRREDDY.NS", "name": "Dr. Reddy's Laboratories Ltd.", "sector": "Healthcare"},
    {"symbol": "EICHERMOT.NS", "name": "Eicher Motors Ltd.", "sector": "Automobile"},
    {"symbol": "GRASIM.NS", "name": "Grasim Industries Ltd.", "sector": "Construction Materials"},
    {"symbol": "HCLTECH.NS", "name": "HCL Technologies Ltd.", "sector": "Information Technology"},
    {"symbol": "HDFCBANK.NS", "name": "HDFC Bank Ltd.", "sector": "Financial Services"},
    {"symbol": "HDFCLIFE.NS", "name": "HDFC Life Insurance Company Ltd.", "sector": "Financial Services"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp Ltd.", "sector": "Automobile"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco Industries Ltd.", "sector": "Metals & Mining"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever Ltd.", "sector": "Fast Moving Consumer Goods"},
    {"symbol": "ICICIBANK.NS", "name": "ICICI Bank Ltd.", "sector": "Financial Services"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank Ltd.", "sector": "Financial Services"},
    {"symbol": "INFY.NS", "name": "Infosys Ltd.", "sector": "Information Technology"},
    {"symbol": "ITC.NS", "name": "ITC Ltd.", "sector": "Fast Moving Consumer Goods"},
    {"symbol": "JSWSTEEL.NS", "name": "JSW Steel Ltd.", "sector": "Metals & Mining"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotak Mahindra Bank Ltd.", "sector": "Financial Services"},
    {"symbol": "LT.NS", "name": "Larsen & Toubro Ltd.", "sector": "Construction"},
    {"symbol": "M&M.NS", "name": "Mahindra & Mahindra Ltd.", "sector": "Automobile"},
    {"symbol": "MARUTI.NS", "name": "Maruti Suzuki India Ltd.", "sector": "Automobile"},
    {"symbol": "NESTLEIND.NS", "name": "Nestle India Ltd.", "sector": "Fast Moving Consumer Goods"},
    {"symbol": "NTPC.NS", "name": "NTPC Ltd.", "sector": "Power"},
    {"symbol": "ONGC.NS", "name": "Oil & Natural Gas Corporation Ltd.", "sector": "Oil, Gas & Consumable Fuels"},
    {"symbol": "POWERGRID.NS", "name": "Power Grid Corporation of India Ltd.", "sector": "Power"},
    {"symbol": "RELIANCE.NS", "name": "Reliance Industries Ltd.", "sector": "Oil, Gas & Consumable Fuels"},
    {"symbol": "SBILIFE.NS", "name": "SBI Life Insurance Company Ltd.", "sector": "Financial Services"},
    {"symbol": "SBIN.NS", "name": "State Bank of India", "sector": "Financial Services"},
    {"symbol": "SHRIRAMFIN.NS", "name": "Shriram Finance Ltd.", "sector": "Financial Services"},
    {"symbol": "SUNPHARMA.NS", "name": "Sun Pharmaceutical Industries Ltd.", "sector": "Healthcare"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products Ltd.", "sector": "Fast Moving Consumer Goods"},
    {"symbol": "TATAMOTORS.NS", "name": "Tata Motors Ltd.", "sector": "Automobile"},
    {"symbol": "TATASTEEL.NS", "name": "Tata Steel Ltd.", "sector": "Metals & Mining"},
    {"symbol": "TCS.NS", "name": "Tata Consultancy Services Ltd.", "sector": "Information Technology"},
    {"symbol": "TECHM.NS", "name": "Tech Mahindra Ltd.", "sector": "Information Technology"},
    {"symbol": "TITAN.NS", "name": "Titan Company Ltd.", "sector": "Consumer Durables"},
    {"symbol": "TRENT.NS", "name": "Trent Ltd.", "sector": "Consumer Services"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement Ltd.", "sector": "Construction Materials"},
    {"symbol": "WIPRO.NS", "name": "Wipro Ltd.", "sector": "Information Technology"},
]
